# Generated by Django 4.2.9 on 2024-02-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_dead_line_alter_task_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
